services:
  emailanalyser:
    build: .
    # Map host port (override with HOST_API_PORT env var, default 5000)
    ports:
      - "${HOST_API_PORT:-5000}:5000"
    environment:
      - API_PORT=5000
      - OUTPUT_DIR=/app/email_analysis_output
      - FLASK_ENV=production
    volumes:
      - email_data:/app/email_analysis_output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  email_data:
    driver: local